---

- name: setup each client with appropriate user and group for backup
  block:
    - group: name={{ backup_group|default('backup') }} state=present
    - user: 
        name: "{{ backup_user |default('backup') }}" 
        shell: /bin/bash 
        createhome: yes 
        group: "{{ backup_group |default('backup') }}" 
        groups: ~ 
        state: present
      register: new_user
    - file: path="{{ new_user.home }}" owner="{{ backup_user |default('backup')}}" group="{{ backup_group|default('backup') }}" mode=0700 state=directory
    - file: path="{{ new_user.home }}/.ssh" owner="{{ backup_user |default('backup') }}" group="{{ backup_group |default('backup') }}" mode=0700 state=directory
    - command: vault kv get -format=json -field=data kv/hosts/{{ hostname }}/backup_ssh_key
      delegate_to: localhost
      environment:
        VAULT_SKIP_VERIFY: "1"
        VAULT_ADDR: "{{vault_addr}}"
        VAULT_TOKEN: "{{ lookup('env', vault_addr_env_var) }}"
      register: ssh_key
    - set_fact:
        ssh_key_json: "{{ ssh_key.stdout|fromjson }}"     
    - copy: content="{{ ssh_key_json.private_key }}" dest="{{ new_user.home}}/.ssh/id_{{ssh_key_json.type}}" owner={{new_user.name}} mode="0400"
    - copy: content="{{ ssh_key_json.public_key }}" dest="{{ new_user.home}}/.ssh/id_{{ssh_key_json.type}}.pub" owner={{new_user.name}} mode="0644"
     
