---

- name: fail deployment if neither client or backup server set
  fail: msg="You must enable backups to use this role for {{inventory_hostname}}"
  when:
    - "not (backup is defined or backup_server is defined)"

- name: setup ssh keypairs and load into vault for safekeeping
  include_tasks: "do-keypair.yml"      
  with_items:
    - "{{ backup_hosts }}"
  
- name: install borg client backup on target
  include_tasks: "borg-client.yml"
  when:
    - backup|bool|default(False)
    - backup_repo is defined

- name: install borg server on target to support clients using it
  include_tasks: "borg-server.yml"
  when:
    - backup_server|bool|default(False)
    - backup_dir is defined
