---

- name: fail deployment if neither client or backup server set
  fail: msg="You must enable backups to use this role for {{inventory_hostname}}"
  when:
    - "not (backup is defined or backup_server is defined)"

- name: fail deployment if official hostname is not set for correct backup routing
  fail: msg="You must set the ansible invent `hostname` variable to ensure correct routing of backups"
  when:
    - hostname is not defined

- name: setup ssh keypairs and load into vault for safekeeping
  include_tasks: "do-keypair.yml"      
  with_items:
    - "{{ backup_hosts }}"
    - "{{ hostvars[backup_server]['hostname'] }}"

- name: install borg client backup on target
  include_tasks: "borg-client.yml"
  when:
    - backup|default(False)|bool
    - backup_repo is defined

- name: install borg server on designated backup server {{hostname}}
  include_tasks: "borg-server.yml"
  when:
    - "inventory_hostname == backup_server"
    - backup_dir is defined
