---

- name: Add repo ppa:liujianfeng1994/rockchip-multimedia
  ansible.builtin.apt_repository:
    repo: ppa:liujianfeng1994/rockchip-multimedia

- name: Copy apt priority for rockchip-multimedia
  copy:
    src: rockchip-multimedia-ppu
    dest: /etc/apt/preferences.d/rockchip-multimedia-ppu
    mode: '0644'
    backup: no

- name: Install mali-g610-firmware
  apt:
        name: mali-g610-firmware
        state: present
  
    
- name: Copy 11-rockchip-multimedia.rules
  copy:
    src: 11-rockchip-multimedia.rules
    dest: /etc/udev/rules.d/11-rockchip-multimedia.rules
    mode: '0644'
    backup: no

- name: upgrade the OS
  include_tasks: "upgrade_host.yml"

- name: Copy HDMI-OUT.conf 
  copy:
    src: HDMI-OUT.conf
    dest: /usr/share/alsa/cards/HDMI-OUT.conf
    mode: '0644'
    backup: no

- name: Add HDMI to alsa card
  lineinfile:
    path: /usr/share/alsa/cards/aliases.conf
    line: rockchip-hdmi0 cards.HDMI-OUT
    insertbefore: BOF


