---

- name: only ubuntu 22.04 or ubuntu 24.04 are supported
  fail: msg="Only Ubuntu 22.04 or 24.04 with the 6.1.x vendor kernel are supported at this time"
  when:
    - (not is_sbc_rk35xx) or (not is_kernel_vendor) or (ansible_distribution_major_version not in ('22', '24'))

- name: get list of running modules
  command: lsmod
  register: lsmod_output

- name: fail deployment if panthor or panfrost module not loaded
  fail: msg="{{inventory_hostname}} does not have either panfrost or panthor modules operational - must be manually fixed for safety"
  when:
    - "lsmod_output is failed or ('panfrost' not in lsmod_output.stdout and 'panthor' not in lsmod_output.stdout)"

# MUST BE BEFORE apt repo's are added as we may nuke old apt repo's in favour of the new ones...
- name: fix existing ld.so and library issues on target host iff forced - MESSY AND DANGEROUS
  include_tasks: "fix-library-mess.yml"
  when: 
    - "force|default(False)|bool"

- name: add kisak mesa apt repo
  template:
    src: templates/mesa.list.j2
    dest: /etc/apt/sources.list.d/kisak-ubuntu-kisak-mesa-noble.sources
    owner: root
    group: root
    mode: "0644"

- name: add multimedia apt repo
  template: 
    src: templates/multimedia.list.j2
    dest: /etc/apt/sources.list.d/liujianfeng1994-ubuntu-rockchip-multimedia-{{ansible_distribution_release|lower}}.sources
    owner: root
    group: root
    mode: "0644"

- name: update apt cache before we do any installs
  apt: update_cache=yes

- name: set oddball packages to install based on ubuntu 24 and later systems
  set_fact:
    noble_packages: 
      - "libwidevinecdm0"
      - "glmark2-x11"
      - "glmark2-es2-x11"
      - "gstreamer1.0-rockchip1"
  when:
    - '"jammy" not in ansible_distribution_release|lower'

- name: set oddball packages for jammy
  set_fact:
    jammy_packages: 
      - "libwidevinecdm"
  when:
   - '"jammy" in ansible_distribution_release|lower'

- name: purge existing mali packages just in case something odd...
  shell: DEBIAN_FRONTEND=noninteractive apt remove -y {{item}}
  ignore_errors: yes  # ok if not found
  with_items:
    - libmali-valhall-g610-g13p0-wayland-gbm
    - libmali-valhall-g610-g6p0-wayland-gbm
    - libmali-valhall-g610-g24p0-wayland-gbm

- name: install hardware accel driver and firmware using user-specified config
  block:
    - command: wget -O /tmp/libmali.deb {{mali_url}}
    - command: dpkg -i /tmp/libmali.deb
    - file: state=absent path=/tmp/libmali.deb

- name: if force requested, ensure that all packages are re-installed at latest available versions
  set_fact:
    force_reinstall_flags: "{{(force|default(False)|bool)|ternary('--upgrade --reinstall', '')}}"

- name: get key packages down for all systems in an ORDERED and somewhat forcible manner
  shell: DEBIAN_FRONTEND=noninteractive apt install -yq {{force_reinstall_flags}} --install-recommends {{item}}
  with_items:
    - libgbm1    # need this to ensure that a forcible delete above is repaired... and thus a "clean" system restored
    - libv4l-0   # must be installed before rockchip-multimedia
    - libv4l-rkmpp
    - libopengl0
    - libgles1
    - libgles2
    - libgles-dev
    - libgles2-mesa-dev
    - libglu1-mesa
    - libegl-mesa0
    - libegl-dev
    - libegl1
    - libgl1
    - libgl1-mesa-dev
    - libgl1-mesa-dri
    - libglvnd0
    - libglx0
    - libglx-mesa0
    - libglapi-mesa
    - librga2 
    - librockchip-mpp1 
    - librockchip-vpu0 
    - mesa-utils  # needed for eglinfo below
    - mesa-utils-extra
    - glmark2
    - "{{ jammy_packages|default([]) }}"
    - "{{ noble_packages|default([]) }}"
    - glmark2-wayland
    - glmark2-es2-wayland 
    - glmark2-es2
    - rockchip-multimedia-config
    - rockchip-mpp-demos
    - mesa-vdpau-drivers  # mostly useful to those with external GPUs...
    - mesa-va-drivers 
    - mesa-vulkan-drivers

- name: fail deployment iff armbian firmware package not installed
  block:
    - stat: path=/lib/firmware/arm/mali/arch10.8/mali_csffw.bin 
      register: mali_fw
    - fail: msg="Armbian Mali firmware package not installed, failure is certain"
      when: 
        - not mali_fw.stat.exists

- name: prefer armbian firmware only when forced
  copy: 
    dest:  /lib/firmware/mali_csffw.bin 
    src:   /lib/firmware/arm/mali/arch10.8/mali_csffw.bin 
    remote_src: yes
    owner: root
    group: root
    mode: "0644"
  register: new_fw

- name: reboot iff new firmware installed to activate it
  reboot:
  become: yes
  when:
    - new_fw is changed
 
# cant make this work on khadas2 edge uefi board - disabled till i figure out why "egl initialize failed" 
#- name: run eglinfo to verify driver is operational or fail deployment fast
#  block:
#    - command: eglinfo -B
#      register: eglinfo_output
#    - assert:
#        that:
#          - '"mali" in eglinfo_output.stdout|lower'
#          - '"panthor" in eglinfo_output.stdout or "panfrost" in eglinfo_output.stdout'
#          - '"kisak" in eglinfo_output.stdout'

- name: install opencl
  include_tasks: "opencl.yml"

- name: install rkmppenc
  include_tasks: "rkmppenc.yml"

- name: install ffmpeg
  include_tasks: "ffmpeg.yml" 
