---

- name: add ssh user to video group without changing the password
  ansible.builtin.user: name="{{ansible_ssh_user}}" append=yes groups=video update_password=on_create

- name: fetch deb package from github
  command: wget -O /tmp/rkmppenc.deb https://github.com/rigaya/rkmppenc/releases/download/0.10/rkmppenc_0.10_Ubuntu{{ansible_distribution_major_version}}.04_arm64.deb

- name: install rkmppenc
  command: dpkg -i /tmp/rkmppenc.deb

- name: cleanup
  file: path=/tmp/rkmppenc.deb state=absent
