---

# ensure facts are available to implement custom logic per SBC
- hosts: all
  roles:
    - sbc-facts

- name: harden targets iff requested BEFORE system gets changed too much
  hosts: all
  become: no
  handlers:
    - import_tasks: handlers/handlers.yml
  tasks:
    - include_role: name="harden"
      when:
         - is_ubuntu   
         - harden|default(False)|bool
    - name: explicitly reboot now to verify that host reboots correctly -it may not if harden does bad things
      reboot: 
      become: yes
      when:
         - is_ubuntu
         - harden|default(False)|bool

- name: provision basics for all targets
  hosts: all
  become: yes
  handlers:
    - import_tasks: handlers/handlers.yml
  roles:
    - no-swap
    - no-boot-logo
    - disable-root-account
    - set-hostname
    - set-timezone
    - sysctl
    - dns-resolver
    - firewall  # assumes firewall rules dont break DNS resolution or ssh...
    - user-ssh-authorized-key
    - extra-software
    - input-remapper
    - role: docker
      when:
        - "docker|default(False)|bool"
    - sshfs
    - role: chrony
    - apt  # we do apt quite late since we need resolver, firewall and other stuff operational first
    - role: nfs-client
      when: 
        - nfs_mounts is defined
    - role: nfs-server
      when:
        - nfs_exports is defined
    - role: disable-leds
      when:
        - disable_leds is defined
    - role: cpufreq
      when:
        - cpu_governor is defined

# on desktop hosts provision what was requested.. 
#- hosts: desktops
#  become: yes
#  roles:
#    - include_role: name="gdm-auto-login"
#    - include_role: name="gdm-enable-wayland"
#    - window-manager # sddm for kde, gdm for gnome
#    - ubuntu-desktop-minimal
#      when: 
#        - "desktop == 'minimal' or desktop == 'ubuntu'"
#    - kde-plasma
#      when:
#        - "desktop == 'kde-plasma' or desktop == 'kde'"
#    - gnome
#      when:
#        - "desktop == 'gnome' 
#    - firefox-no-snap
#    - role: orangepi5-hdmi
#      when:
#        - is_armbian
#        - is_sbc_rk35xx
#        - is_sbc_opi5 or is_sbc_opi5_plus

# provision multimedia after desktop since often dependent on X/Wayland etc.
- hosts: all
  become: yes
  roles:
    - role: multimedia
      when: 
        - "multimedia|default(False)|bool"
    - role: ai
      when:
        - "ai|default(False)|bool"

# only provision gdm if host is in appropriate group
- hosts: desktops
  tasks:

# kodi group hosts get kodi installed at a host level using debian packages 
- hosts: desktops kodi
  become: yes
  roles:
    - hdmi-audio-dts-a52
    - kodi 

- hosts: lg
  become: yes
  roles:
    - role: lgtv
    - role: surround-sound-test

- hosts: vault
  any_errors_fatal: yes # failure of a node, means failure of the cluster...
  roles:
    - hashicorp-vault

- hosts: wazuh_manager
  become: yes
  roles:
    - wazuh-server-all-in-one

- hosts: mosquitto
  roles:
    - mosquitto
