---

- name: ensure required software is present
  apt: name=bind9-host state=latest

- name: install resolved.conf with configured deployment settings
  template: 
    src: templates/resolved.conf.j2 
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: "0644" # must be world readable to avoid perm denied error

- name: purge default armbian config to ensure template settings only are in effect
  file: state=absent path=/etc/systemd/resolved.conf.d

- name: enable systemd-resolved service
  systemd: enabled=yes masked=no daemon_reload=yes state=restarted name=systemd-resolved

- name: ensure /etc/resolv.conf points to systemd-resolved
  command: ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf

- name: fail deployment if its not working
  command: host www.theage.com.au 127.0.0.53
  register: required_results

- name: fail deployment if no address records found
  fail: msg="No address records returned - DNS is not working on {{inventory_hostname}}"
  when: 
    - "'has address' not in required_results.stdout"

- command: resolvectl status
  register: resolvectl_status

- name: but also fail deployment if resolvectl doesnt report configured ip's
  fail: msg="Requested DNS server was not configured correctly - {{item}} is not present in `resolvectl status`"
  when:
    - "item not in resolvectl_status.stdout"
  with_items:
    - "{{ dns_primary_servers |default([]) }}"
    - "{{ dns_fallback_servers |default([]) }}"
