---

- name: rsyslog service and socket is switched off
  systemd: name={{item}} state=stopped enabled=no masked=yes daemon_reload=yes
  become: yes
  with_items:
    - "rsyslog.service"
    - "syslog.socket"
