- name: Disable ipv6 net.ipv6.conf.all.disable_ipv6=1
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    state: present

- name: Disable ipv6 net.ipv6.conf.default.disable_ipv6=1
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    state: present
