---

- name: ensure required packages are present
  apt:
    pkg:
      - gpg
      - wget
 
- name: add hashicorp vault repo to target hosts
  command: wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: ensure vault apt repo is installed
  command: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

- name: install vault
  apt: update=yes name=vault state=latest

- name: ensure systemd is ready and activate vault nodes
  systemd: daemon_reload=yes masked=no enabled=yes state=restarted name=vault


