---

- name: ensure mounts are in fstab
  lineinfile:
    line: "{{ item.svr_path }} {{item.mount}} {{item.fstype|default('nfs4')}} {{ item.mount_opts|default('rw,async,noauto,x-systemd.automount,nofail') }}"
    insertafter: EOF
    regexp: "^{{item.svr_path}}\\s" # not extra space to handle subpath mounts
    path: /etc/fstab
  with_items:
    - "{{ nfs_mounts }}"
  when:
    - nfs_mounts is defined
  register: mount_results

- name: ensure mount points exist
  file: state=directory path={{item.mount}} mode="0755" owner=root group=root
  with_items:
    - "{{ nfs_mounts }}"
  when:
    - nfs_mounts is defined
  register: mount_point_results

- name: ensure systemd knows about fstab changes, iff any
  block:
    - name: notify systemd of changes
      systemd: daemon_reload=yes
    - name: remount filesytems explicitly during run to check for connectivity
    - name: command: mount -av
  when:
    - nfs_mounts is defined
    - mount_results is changed or mount_results is success or mount_point_results is changed

