---

- name: ensure nfs-common is installed
  apt: name=nfs-common state=present

- name: perform mounts via fstab 
  include_tasks: "fstab_mounts.yml"
  when:
    - nfs_mounts is defined
    - nfs_mounts|length > 0
