---


- name: populate automount and mount files from nfs_mounts
  block:
    - template:
        src: templates/mount.j2
        dest: /etc/systemd/system/mnt-{{item.mount|basename}}.mount
        owner: root
        group: root
        mode: "0644"
      with_items:
        - "{{ nfs_mounts }}'
    - template:
        src: templates/automount.j2
        dest: /etc/systemd/system/mnt-{{item.mount|basename}}.automount
        owner: root
        group: root
        mode: "0644"
      with_items:
        - "{{ nfs_mounts }}"
    - systemd: daemon_reload=yes enabled=yes state=restarted masked=no mnt-{{item.mount|basename}}.automount
      with_items:
        - "{{ nfs_mounts }}"
