---

# currently not called, if favour of a custom fork...
- name: ensure python venv is present
  apt: name=python{{ansible_python.version.major}}.{{ansible_python.version.minor}}-venv state=latest 

- name: clone RKNN-LLM to {{ai_home}} if not already
  command: git clone https://github.com/airockchip/rknn-llm.git
  become_user: "{{ai_user|default('root')}}"
  args:
    chdir: "{{ai_home}}"
    creates: "{{ai_home}}/rknn-llm/README.md"


- name: install rknn LLM runtime to /usr/lib64 BUT DO NOT override an existing library
  copy: src="{{ai_home}}/rknn-llm/rkllm-runtime/Linux/librkllm_api/{{ansible_architecture}}/librkllmrt.so" dest="/usr/lib64" owner=root group=root mode="0755" remote_src=yes force=no

- name: pip install rknn-llm toolkit
  pip: name="{{ ai_llm_toolkit_wheel|default('rkllm_toolkit-1.1.4-cp310-cp310-linux_x86_64.whl') }}" state=present
  args:
    chdir: "{{ ai_home }}/rknn-llm/rkllm-toolkit/packages/"
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: "1"

