---

# this must be disabled since a boot failure will result on the hardened systems
- name: disable ZRAM swap and logging
  block:
    - lineinfile: 
        path: /etc/default/armbian-zram-config
        line: ENABLED=false
        regexp: ^ENABLED
        state: present
    - lineinfile:
        path: /etc/fstab
        line: "#/dev/zram mount disabled by ansible harden role"
        regexp: ^/dev/zram
        state: absent
      register: mounts_removed
    - systemd: name="{{item}}" state=stopped masked=yes enabled=no daemon_reload=yes
      with_items:
        - armbian-zram-config 
        - armbian-ram-logging
      ignore_errors: yes # ok if service not present on target
    - systemd: daemon_reload=yes  # ensure systemd is aware of fstab changes
      when: 
        - mounts_removed is changed 
        
